### ISSUE TITLE
Map style

### ISSUE THREAD

**Issue by danielblom** [boopeshmahendran/AdobeXD-maps#1]
Feature request: Ability to tweak the style of the map.
1. Would be nice to be able to generate the map without a location pin. I (and I assume many other designers) like to design the location pin myself.
2. Be able to style the map. I.e. by pasting JSON style like you can do on Google Maps style wizard: https://mapstyle.withgoogle.com/

**Comment by boopeshmahendran** [comment]
Hi @danielblom Thank you very much for using my plugin and filing a feature request. I will try to add this feature as soon as possible.

**Comment by boopeshmahendran** [comment]
@danielblom I have added the options for disabling the location pin and also adding styles. They should be available in v1.1.0. Please feel free to give feedback. Thanks.

**Comment by danielblom** [comment]
@boopeshmahendran Incredible work and fast delivery! All works correctly and stable, I use Maps a lot when designing, so I will stay on the lookout for bugs or improvements.

Thank you for making designers life a bit easier with this great plugin 🙏🏽

**Comment by danielblom** [comment]
@boopeshmahendran I can no longer find/install the XD plugin. Did you remove it?
