### ISSUE TITLE
Run without selection and other improvements 

### ISSUE THREAD

**Issue by samdotdesign** [boopeshmahendran/AdobeXD-maps#3]
Hey there! I'm a designer on the XD team at Adobe and an avid fan of maps of all types — so I love your plugin! I have some feedback.

- I would love to be able to run this plugin without any selection. Perhaps it would just paste onto the canvas at a reasonable size. 
- I think you could do without the success message. Only if there is an error do you need to show another dialog after running the plugin. 
- Would be nice to have images with an example city to show what the zoom levels look like. 
- Lastly, retaining the settings of the last time the plugin was run would be handy!

I made a mockup with some design tweaks: 
![image](https://user-images.githubusercontent.com/14067203/57104537-764f6e00-6cdd-11e9-8e55-18fd2cc6341d.png)

I recommend putting the check box before a string instead of after.
Here's the asset for the zoom level examples if you'd like to use it:
![image](https://user-images.githubusercontent.com/14067203/57104430-27093d80-6cdd-11e9-9b89-83c6570e961a.png)

EDIT: One more thing! Would also be awesome to see/select the map type with examples. 
![image](https://user-images.githubusercontent.com/14067203/57105502-c62f3480-6cdf-11e9-91f3-4a303a8781f0.png)

**Comment by pklaschka** [comment]
A comment about the retaining setttings: I think it would be great if the settings were saved on a per-node basis (@samdotdesign it's not quite clear whether you mean that or the settings of previously running the plugin). 

@boopeshmahendran This should also be quite easy to achieve with `node.pluginData` – see https://adobexdplatform.com/plugin-docs/reference/scenegraph.html#scenenodeplugindata--

**Comment by boopeshmahendran** [comment]
Thanks very much for using the plugin @samdotdesign and I very much appreciate your valuable feedback and the mockups you have provided. @pklaschka Thanks for your suggestion.

 I will try to incorporate these changes in few days and will keep you guys posted.

**Comment by boopeshmahendran** [comment]
Hi @samdotdesign and @pklaschka , I have made the required changes and am attaching a screenshot of the new UI.

<img width="728" alt="Map generator new UI" src="https://user-images.githubusercontent.com/21012100/57196981-79698900-6f7f-11e9-9c95-2033c29ce10c.png">

**Changed things:**
- Add zoom level example image and also make it clickable to change zoom level
- Change map type UI
- Retain values per session
- Change Location Pin UI

**Regarding retaining settings:** I thought you meant saving settings per session and I have implemented the same.
**Regrading run without selection:** I think giving a selection error when there is no selection is fine. My opinion is that It lets the user know which kind of layers are supported and also most of the other plugins behave in the same way. 

I have created a prerelease [here](https://github.com/boopeshmahendran/AdobeXD-maps/releases/tag/1.2.0-alpha) in case you guys want to use it and give feedback.

@samdotdesign and @pklaschka Awaiting your feedback.

**Comment by samdotdesign** [comment]
@boopeshmahendran This is so awesome! I love that you made the zoom image clickable too. 
One thing I notice is alignment of various elements. They stagger left and right a little. Some more vertical padding between elements would also give it more breathing room (see bottommost design — about 14 points between sections).
![image](https://user-images.githubusercontent.com/14067203/57247677-537ecb80-6ff5-11e9-9df4-8f2c2f29e0f9.png)
As for the map type selector, I think something shorter like the asset I shared before would suffice. Covering the image with the name makes it hard to see the map itself. Also Chicago looks pretty similar when comparing Roadmap to Terrain. My design uses the area Marin, California which seems to show all map types well. I've also been thinking about how someone can select which type. I've branched off your idea with the checkmark – but just a bit simplified. 
![image](https://user-images.githubusercontent.com/14067203/57247939-018a7580-6ff6-11e9-9d01-7dd37ea33a42.png)
(If we move the name of the selected map type to next to the label, we can move it for Zoom selection too.)
Here's the 16x16 checkmark asset if you'd like to use it. 
![checkbox@3x](https://user-images.githubusercontent.com/14067203/57248380-0e5b9900-6ff7-11e9-8758-fff18a507514.png)

**Comment by boopeshmahendran** [comment]
@samdotdesign Thanks a lot for reviewing and providing newer designs and assets. I have updated the UI as per the design as close as possible and attached a screenshot below. There are still minor alignment issues, but it seems to be difficult to fix them and I think it is very negligible.
Please review it once and provide your feedback.

<img width="1280" alt="maps generator new UI" src="https://user-images.githubusercontent.com/21012100/57325492-c2f4d800-7127-11e9-95a7-467390e844c3.png">

**Comment by samdotdesign** [comment]
Ahhh! @boopeshmahendran this is **stellar!** I love it. Hopefully the users love it too.

**Comment by boopeshmahendran** [comment]
Thanks a lot for your designs and review @samdotdesign . I have created a release with the changes. https://github.com/boopeshmahendran/AdobeXD-maps/releases/tag/1.2.0 . And it should be available in XD plugin manager in few days. Closing this issue.
